### ISSUE TITLE
Support for .png images

### ISSUE THREAD

**Issue by Jesse-V** [Jesse-V/iVoxely#6]
MappedModel.cpp can currently load a .bmp file, and TextureMap.cpp class has proven to handle even .bmp over 100MB in size. However, .bmp images are uncompressed, and thus quite large. For this reason, they are not as common as other formats such as .png and .jpg. It would be nice if the code also supported .png images, which are significantly smaller than .bmp files, and are much more common.

LodePNG, png++, and libpng are some libraries to look at.

Some links that might be helpful include:
http://stackoverflow.com/questions/11296644/loading-png-textures-to-opengl-with-libpng-only
http://stackoverflow.com/questions/2703255/need-help-using-libpng-to-read-an-image
http://codereview.stackexchange.com/questions/10477/png-filereader-implementation-in-c-using-libpng
http://www.gamedev.net/topic/622828-how-to-read-png-images-without-a-library/
http://www.cplusplus.com/forum/general/71630/

**Comment by pcm2718** [comment]
PNG support is now functional, though improvements may be needed in the future. libpng and png++ are now prerequisites to iVoxely.

**Comment by Jesse-V** [comment]
Did you know you can say something like "closed #6" in your git commit and Github will close the ticket automatically? For example, you could say **git commit -m "fixed #6 using png++/libpng"** and the ticket would be closed when you merged that commit into the master branch.

See https://github.com/blog/831-issues-2-0-the-next-generation
